### ISSUE TITLE
browser.d.ts not found when doing ng-serve

### ISSUE THREAD

**Issue by lintu** [jelbourn/material2-app#14]
I am getting the following error when trying to do ng-serve.

**The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:**
Error: Typescript found the following errors:
  material2-app/tmp/broccoli_type_script_compiler-input_base_path-j7f4G37d.tmp/0/src/typings.d.ts (1, 1): File 'material2-app/tmp/broccoli_type_script_compiler-input_base_path-j7f4G37d.tmp/0/typings/browser.d.ts' not found.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (material2-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:12
0:19)
    at BroccoliTypeScriptCompiler.build (material2-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at material2-app\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (material2-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (material2-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (material2-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (material2-app\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

What I did
1. Cloned the repo
2. Did `npm install`
3. `ng-serve`

**Comment by prashant162** [comment]
From src/typings.d.ts remove the line

"reference path="../typings/browser.d.ts" completely there should be just one line like:

declare var module: { id: string };

and then try again.
