### ISSUE TITLE
NPM START failed after a successful NPM INSTALL

### ISSUE THREAD

**Issue by cbeldacap** [jelbourn/material2-app#21]
The command throws this error....

```
Cannot read property 'AssetUrl' of undefined
TypeError: Cannot read property 'AssetUrl' of undefined
    at Object.<anonymous> (C:\DevonFactory\NjordWeb\material2-app-master\node_modules\@angular\compiler-cli\src\private_import_compiler.js:10:51)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    (...)
```

**Comment by hbekkouche** [comment]
same problem for me

**Comment by mapiram** [comment]
I've the same problem.
It seems an issue related to @angular/compiler-cli. Same bad result with its versions 0.6.3 and 0.6.4

**Comment by hbekkouche** [comment]
~~I Try this and it work for me~~
- ~~delete node_modules~~
- ~~do a fresh npm i angular-cli@1.0.0-beta.18 -g~~
- ~~do again ng init~~
- ~~Y --> override package.json~~

~~con you confirm.~~

**Comment by Fiontan** [comment]
Same issue. haven't tried @hbekkouche proposal...has anyone?

**Comment by Fiontan** [comment]
@hbekkouche your proposal will overwrite teh package.json and so the npm install will not add material

**Comment by ankurlalit** [comment]
Same issue.

**Comment by Fiontan** [comment]
@hbekkouche 's approach works although you will need to take care with over writing files with ng init (or you may not have to worry depending on whether you have added anything or not) and will be prompted in the command line for each file that ng init creates. After this, you must manually add the reference to the compatible version of material to package.json and then do another npm install which will not take as long as the initial run.. @ankurlalit

**Comment by RyderMS** [comment]
@hbekkouche I tried your instructions, making sure to carefully not override any of the other files in the project when prompted, but its still throwing same error.
