### ISSUE TITLE
Example app is not work!

### ISSUE THREAD

**Issue by ColdSIce** [jelbourn/material2-app#45]
1. git clone ...
2. cd in and npm install
3. ng serve

`Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
    at Object.resolveEntryModuleFromMain (/home/alekhin/workspace/angular2/material-from-git/material2-app/node_modules/@ngtools/webpack/src/entry_resolver.js:128:11)
    at AotPlugin._setupOptions (/home/alekhin/workspace/angular2/material-from-git/material2-app/node_modules/@ngtools/webpack/src/plugin.js:142:50)
    at new AotPlugin (/home/alekhin/workspace/angular2/material-from-git/material2-app/node_modules/@ngtools/webpack/src/plugin.js:26:14)
    at Object.exports.getNonAotConfig (/home/alekhin/workspace/angular2/material-from-git/material2-app/node_modules/angular-cli/models/webpack-configs/typescript.js:26:13)
    at new NgCliWebpackConfig (/home/alekhin/workspace/angular2/material-from-git/material2-app/node_modules/angular-cli/models/webpack-config.js:24:37)
    at Class.run (/home/alekhin/workspace/angular2/material-from-git/material2-app/node_modules/angular-cli/tasks/serve.js:31:29)
    at /home/alekhin/workspace/angular2/material-from-git/material2-app/node_modules/angular-cli/commands/serve.run.js:22:22
    at process._tickCallback (internal/process/next_tick.js:103:7)
`

If I'll update all dependencies, I've get the same exception...

Why your example is not work "from box"?

**Comment by Rocky-L** [comment]
I've got the same error

**Comment by DavidDavila** [comment]
same!

**Comment by m67hoff** [comment]
Hy Jeremy,

I had the same error.  I updated my fork to  the latest material 2.0.0-beta.3 / angular 4.0.0  / cli 1.0.1.
My updated fork :  https://github.com/m67hoff/material2-sample
This is now working and also the deprecated  md-sidenav-layout / md-input is updated.

**Does it make sense, if I send you a pull request ?**   ( I'm a beginner and so not 100% sure if everything I changed is in line with your standard )

**Comment by DarylBerryhill** [comment]
the example app IS WORKING for me.  [https://material2-app.firebaseapp.com/](url) 

However copying the code into a Angular V4 ng-cli project doesn't work. ng serve compiles without errors. however there are a ton of errors in the browser.  The example App IS WORKING but it is using angular 2. maybe a compatibility problems. Umm lets check the ng2 to ng 4 migration docs

**Comment by m67hoff** [comment]
Daryl - we are not talking about looking at the ready deployed & running  WebURL ( https://material2-app.firebaseapp.com )  this was setup some monthe ago and sure its still up&running. 
BUT:  This is a "programmers example"  and at the moment building & running it locally is not working (unmodified).  This is either because: The code is not updated to the latest material2 version and it uses some deprecated things or because the versions in package.json are not fixed.  (However: the second "fix" does not make sense since it is official recommended at  https://material.angular.io/guide/getting-started as code starter sample)

Anyway: Seems they have more work to do and can not support this sample at the moment. My recommendation is there are manny forks to this sample with updated code. 
( like https://github.com/aveferrum/angular-material-demo  )
